const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Button.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{DragDrop: 0},
	{Racket: 0},
	{Ground: 0},
	{Start: 0},
	{Mouse: 0},
	{Stop: 0},
	{HitBlock: 0},
	{Keyboard: 0},
	{SpriteFont: 0},
	{points: 0},
	{pointsnum: 0},
	{outofbounds: 0},
	{Spike: 0},
	{hitspikes: 0},
	{hitspikesnum: 0},
	{hitcubes: 0},
	{hitcubesnum: 0},
	{youlosttext: 0},
	{Button: 0},
	{Particles: 0},
	{Particles2: 0},
	{Audio: 0},
	{RacketMENU: 0},
	{teenenseagameine: 0},
	{startMENU: 0},
	{settingsMENU: 0},
	{Tutmenutext: 0},
	{settingstextafaj: 0},
	{Shakyness: 0},
	{Back: 0},
	{RareBlueCircle: 0},
	{Particles3: 0},
	{Extreme_Mode: 0},
	{Points: 0},
	{blockhit: 0},
	{spikehit: 0},
	{timenum: 0},
	{ShakeEnabled: 0},
	{ExtremeEnabled: 0}
];

self.InstanceType = {
	Racket: class extends self.ISpriteInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	Start: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Stop: class extends self.ITiledBackgroundInstance {},
	HitBlock: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	points: class extends self.ITextInstance {},
	pointsnum: class extends self.ITextInstance {},
	outofbounds: class extends self.ITiledBackgroundInstance {},
	Spike: class extends self.ISpriteInstance {},
	hitspikes: class extends self.ITextInstance {},
	hitspikesnum: class extends self.ITextInstance {},
	hitcubes: class extends self.ITextInstance {},
	hitcubesnum: class extends self.ITextInstance {},
	youlosttext: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	RacketMENU: class extends self.ISpriteInstance {},
	teenenseagameine: class extends self.ITextInstance {},
	startMENU: class extends self.ISpriteInstance {},
	settingsMENU: class extends self.ISpriteInstance {},
	Tutmenutext: class extends self.ITextInstance {},
	settingstextafaj: class extends self.ITextInstance {},
	Shakyness: class extends self.IButtonInstance {},
	Back: class extends self.IButtonInstance {},
	RareBlueCircle: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Extreme_Mode: class extends self.IButtonInstance {}
}